# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-28 03:29:52
"""
import arcpy

def Model():  # Modèle

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    _mview_eau_bornes_fontaines = "_mview_eau_bornes_fontaines"
    Ogou1 = "Ogou1"

    # Process: Découper (Découper) (analysis)
    borneFontaine_Ogou1 = "H:\\Master_Avignon\\Self_didact\\Arcgis_pro\\Projet_MB\\Projet_MB.gdb\\_mview_eau_bornes_fonta_Clip"
    arcpy.analysis.Clip(in_features=_mview_eau_bornes_fontaines, clip_features=Ogou1, out_feature_class=borneFontaine_Ogou1)

    # Process: Zone tampon (Zone tampon) (analysis)
    Tampon_1kmFontaine = "H:\\Master_Avignon\\Self_didact\\Arcgis_pro\\Projet_MB\\Projet_MB.gdb\\_mview_eau_bornes_fon_Buffer"
    arcpy.analysis.Buffer(in_features=borneFontaine_Ogou1, out_feature_class=Tampon_1kmFontaine, buffer_distance_or_field="1 Kilometers", dissolve_option="ALL")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="H:\\Master_Avignon\\Self_didact\\Arcgis_pro\\Projet_MB\\Projet_MB.gdb", workspace="H:\\Master_Avignon\\Self_didact\\Arcgis_pro\\Projet_MB\\Projet_MB.gdb"):
        Model()
